# This is a basic workflow to help you get started with Actions

name: Update codebook

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a  job called "create_docs"
  create_docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[noaction]')"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: install wkhtml
      run: sudo apt-get install wkhtmltopdf xvfb
    - name: install R dependencies
      run: sudo apt-get install libcurl4-openssl-dev libxml2-dev
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Create temp directory
      run: "[[ -d temp ]] || mkdir temp "

    # Runs a set of commands using the runners shell
    - name: Run docker for R 
      uses: docker://rocker/r-verse
      with:
          args: "Rscript --vanilla _programs/master.R "
          
    - name: Convert HTML to PDF
      run: "/usr/bin/xvfb-run /usr/bin/wkhtmltopdf README.html README2.pdf"
    # send it up
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.4.9
      with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
